"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ngrx_forms_1 = require("./ngrx-forms");
describe('ngrx-forms', function () {
    it("should export " + ngrx_forms_1.isArrayState.name, function () { return expect(ngrx_forms_1.isArrayState).toBeDefined(); });
    it("should export " + ngrx_forms_1.isGroupState.name, function () { return expect(ngrx_forms_1.isGroupState).toBeDefined(); });
    it("should export " + ngrx_forms_1.cast.name, function () { return expect(ngrx_forms_1.cast).toBeDefined(); });
    it("should export " + ngrx_forms_1.createFormControlState.name, function () { return expect(ngrx_forms_1.createFormControlState).toBeDefined(); });
    it("should export " + ngrx_forms_1.createFormGroupState.name, function () { return expect(ngrx_forms_1.createFormGroupState).toBeDefined(); });
    it("should export " + ngrx_forms_1.createFormArrayState.name, function () { return expect(ngrx_forms_1.createFormArrayState).toBeDefined(); });
    it("should export " + ngrx_forms_1.formControlReducer.name, function () { return expect(ngrx_forms_1.formControlReducer).toBeDefined(); });
    it("should export " + ngrx_forms_1.formGroupReducer.name, function () { return expect(ngrx_forms_1.formGroupReducer).toBeDefined(); });
    it("should export " + ngrx_forms_1.formArrayReducer.name, function () { return expect(ngrx_forms_1.formArrayReducer).toBeDefined(); });
    it("should export " + ngrx_forms_1.addArrayControl.name, function () { return expect(ngrx_forms_1.addArrayControl).toBeDefined(); });
    it("should export " + ngrx_forms_1.addGroupControl.name, function () { return expect(ngrx_forms_1.addGroupControl).toBeDefined(); });
    it("should export " + ngrx_forms_1.disable.name, function () { return expect(ngrx_forms_1.disable).toBeDefined(); });
    it("should export " + ngrx_forms_1.enable.name, function () { return expect(ngrx_forms_1.enable).toBeDefined(); });
    it("should export " + ngrx_forms_1.focus.name, function () { return expect(ngrx_forms_1.focus).toBeDefined(); });
    it("should export " + ngrx_forms_1.markAsDirty.name, function () { return expect(ngrx_forms_1.markAsDirty).toBeDefined(); });
    it("should export " + ngrx_forms_1.markAsPristine.name, function () { return expect(ngrx_forms_1.markAsPristine).toBeDefined(); });
    it("should export " + ngrx_forms_1.markAsSubmitted.name, function () { return expect(ngrx_forms_1.markAsSubmitted).toBeDefined(); });
    it("should export " + ngrx_forms_1.markAsTouched.name, function () { return expect(ngrx_forms_1.markAsTouched).toBeDefined(); });
    it("should export " + ngrx_forms_1.markAsUnsubmitted.name, function () { return expect(ngrx_forms_1.markAsUnsubmitted).toBeDefined(); });
    it("should export " + ngrx_forms_1.markAsUntouched.name, function () { return expect(ngrx_forms_1.markAsUntouched).toBeDefined(); });
    it("should export " + ngrx_forms_1.removeArrayControl.name, function () { return expect(ngrx_forms_1.removeArrayControl).toBeDefined(); });
    it("should export " + ngrx_forms_1.removeGroupControl.name, function () { return expect(ngrx_forms_1.removeGroupControl).toBeDefined(); });
    it("should export " + ngrx_forms_1.reset.name, function () { return expect(ngrx_forms_1.reset).toBeDefined(); });
    it("should export " + ngrx_forms_1.setErrors.name, function () { return expect(ngrx_forms_1.setErrors).toBeDefined(); });
    it("should export " + ngrx_forms_1.setUserDefinedProperty.name, function () { return expect(ngrx_forms_1.setUserDefinedProperty).toBeDefined(); });
    it("should export " + ngrx_forms_1.setValue.name, function () { return expect(ngrx_forms_1.setValue).toBeDefined(); });
    it("should export " + ngrx_forms_1.unfocus.name, function () { return expect(ngrx_forms_1.unfocus).toBeDefined(); });
    it("should export " + ngrx_forms_1.updateArray.name, function () { return expect(ngrx_forms_1.updateArray).toBeDefined(); });
    it("should export " + ngrx_forms_1.updateGroup.name, function () { return expect(ngrx_forms_1.updateGroup).toBeDefined(); });
    it("should export " + ngrx_forms_1.updateRecursive.name, function () { return expect(ngrx_forms_1.updateRecursive).toBeDefined(); });
    it("should export " + ngrx_forms_1.validate.name, function () { return expect(ngrx_forms_1.validate).toBeDefined(); });
    it("should export NGRX_STATUS_CLASS_NAMES", function () { return expect(ngrx_forms_1.NGRX_STATUS_CLASS_NAMES).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxFormControlDirective.name, function () { return expect(ngrx_forms_1.NgrxFormControlDirective).toBeDefined(); });
    it("should export NgrxValueConverters", function () { return expect(ngrx_forms_1.NgrxValueConverters).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxFormDirective.name, function () { return expect(ngrx_forms_1.NgrxFormDirective).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxDefaultViewAdapter.name, function () { return expect(ngrx_forms_1.NgrxDefaultViewAdapter).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxCheckboxViewAdapter.name, function () { return expect(ngrx_forms_1.NgrxCheckboxViewAdapter).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxNumberViewAdapter.name, function () { return expect(ngrx_forms_1.NgrxNumberViewAdapter).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxRangeViewAdapter.name, function () { return expect(ngrx_forms_1.NgrxRangeViewAdapter).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxSelectViewAdapter.name, function () { return expect(ngrx_forms_1.NgrxSelectViewAdapter).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxSelectMultipleViewAdapter.name, function () { return expect(ngrx_forms_1.NgrxSelectMultipleViewAdapter).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxRadioViewAdapter.name, function () { return expect(ngrx_forms_1.NgrxRadioViewAdapter).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxSelectOption.name, function () { return expect(ngrx_forms_1.NgrxSelectOption).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxSelectMultipleOption.name, function () { return expect(ngrx_forms_1.NgrxSelectMultipleOption).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxFallbackSelectOption.name, function () { return expect(ngrx_forms_1.NgrxFallbackSelectOption).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxStatusCssClassesDirective.name, function () { return expect(ngrx_forms_1.NgrxStatusCssClassesDirective).toBeDefined(); });
    it("should export " + ngrx_forms_1.NgrxFormsModule.name, function () { return expect(ngrx_forms_1.NgrxFormsModule).toBeDefined(); });
});
//# sourceMappingURL=ngrx-forms.spec.js.map